name: pbl6_mobile
description: A PBL6 Mobile App End-user
version: 2.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  auth:
    path: packages/auth
  category:
    path: packages/category
  constant_helper:
    path: packages/constant_helper
  connectivity_plus: ^3.0.2
  dartx: ^1.1.0
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_lazy_indexed_stack: ^0.0.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  formz: ^0.4.1
  get_it: ^7.2.0
  go_router: 5.2.4
  http: ^0.13.5
  http_client_handler: ^0.1.1
  intl: ^0.17.0
  models:
    path: packages/models
  path: ^1.8.1
  shimmer: ^2.0.0
  widgets:
    path: packages/widgets
  enhanced_multiselect: ^0.1.0
  address:
    path: packages/address
  platform_helper: ^0.1.0
  property:
    path: packages/property
  currency_text_input_formatter: ^2.1.7
  user:
    path: packages/user
  post:
    path: packages/post
  media:
    path: packages/media
  bookmark:
    path: packages/bookmark
  payment:
    path: packages/payment
  booking:
    path: packages/booking
  review:
    path: packages/review
  uptop:
    path: packages/uptop
  config:
    path: packages/config
  notification:
    path: packages/notification
  statistics:
    path: packages/statistics
  cached_network_image: ^3.2.2
  faker: ^2.0.0
  flutter_cache_manager: ^3.3.0
  timeago: ^3.3.0
  package_info_plus: ^3.0.2
  easy_debounce: ^2.0.2+1
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_calendar: ^20.3.57
  syncfusion_localizations: ^20.3.57
  url_launcher: ^6.1.6
  flutter_inappwebview: ^5.7.1+2
  fl_chart: ^0.55.2
  syncfusion_flutter_charts: ^20.3.58
  badges: ^2.0.3
  sentry_flutter: ^6.18.0
  lottie: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

flutter_gen:
  output: lib/app/config/gen/

  integrations:
    flutter_svg: true
    lottie: true
