name: auth
description: An Authentication Module
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  constant_helper:
    path: ../constant_helper
  flutter:
    sdk: flutter
  http_client_handler: ^0.1.1
  json_annotation: ^4.7.0
  models:
    path: ../models
  secure_storage_helper: ^0.1.1
dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
