name: widgets
description: A shared widget packages
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  multiselect:
    path: ../multiselect

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
