name: platform_helper
description: A set of helper for app like image picker
version: 0.1.0+1
publish_to: none


environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
