name: address
description: A very good flutter package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  constant_helper:
    path: ../constant_helper
  flutter:
    sdk: flutter
  http_client_handler: ^0.1.1
  models:
    path: ../models
  secure_storage_helper: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
