import 'package:json_annotation/json_annotation.dart';

enum Permission {
  /// POST permission
  @JsonValue('Booking.Approve.Meeting')
  bookingApproveMeeting,
  @JsonValue('Booking.Confirm.Met')
  bookingConfirmMet,
  @JsonValue('Booking.Create.Meeting')
  bookingCreateMeeting,
  @JsonValue('Booking.View.All.Booked')
  bookingViewAllBooked,
  @JsonValue('Booking.View.All.Personal')
  bookingViewAllPersonal,
  @JsonValue('Bookmark.Create')
  bookmarkCreate,
  @JsonValue('Bookmark.Remove')
  bookmarkRemove,
  @JsonValue('Bookmark.View')
  bookmarkView,
  @JsonValue('ConfigSetting.Update')
  configSettingUpdate,
  @JsonValue('ConfigSetting.View.All')
  configSettingViewAll,
  @JsonValue('ConfigSetting.View.One')
  configSettingViewOne,
  @JsonValue('FreeTime.Create')
  freeTimeCreate,
  @JsonValue('FreeTime.View.All')
  freeTimeViewAll,
  @JsonValue('Notification.Update')
  notificationUpdate,
  @JsonValue('Notification.View.All')
  notificationViewAll,
  @JsonValue('Payment.View.All.History')
  paymentViewAllHistory,
  @JsonValue('Payment.View.All.History.Personal')
  paymentViewAllHistoryPersonal,
  @JsonValue('Permission.Create')
  permissionCreate,
  @JsonValue('Permission.Remove')
  permissionRemove,
  @JsonValue('Permission.View')
  permissionView,
  @JsonValue('Post.Check.Duplicate.Uptop')
  postCheckDuplicateUptop,
  @JsonValue('Post.Create')
  postCreate,
  @JsonValue('Post.Create.Uptop')
  postCreateUptop,
  @JsonValue('Post.Delete')
  postDelete,
  @JsonValue('Post.Get.Uptop')
  postGetUptop,
  @JsonValue('Post.Update')
  postUpdate,
  @JsonValue('Post.View.All.Personal')
  postViewAllPersonal,
  @JsonValue('PostStatistic.View.Detail.In.Date')
  postStatisticViewDetailInDate,
  @JsonValue('PostStatistic.View.In.Date.Range')
  postStatisticViewInDateRange,
  @JsonValue('PostStatistic.View.Top.In.Date')
  postStatisticViewTopInDate,
  @JsonValue('Review.Check.Can.Review')
  reviewCheckCanReview,
  @JsonValue('Review.Create')
  reviewCreate,
  @JsonValue('Role.Create')
  roleCreate,
  @JsonValue('Role.Update')
  roleUpdate,
  @JsonValue('Role.View.All')
  roleViewAll,
  @JsonValue('Role.View.One')
  roleViewOne,
  @JsonValue('User.Update.Account.Access')
  userUpdateAccountAccess,
  @JsonValue('User.Update.Profile')
  userUpdateProfile,
  @JsonValue('User.View.Account.Access')
  userViewAccountAccess,
  @JsonValue('User.View.All')
  userViewAll,
  @JsonValue('User.View.Personal')
  userViewPersonal,
  @JsonValue('UserStatistic.View.Detail.In.Date')
  userStatisticViewDetailInDate,
  @JsonValue('UserStatistic.View.In.Date.Range')
  userStatisticViewInDateRange,
  @JsonValue('UserStatistic.View.Top.In.Date')
  userStatisticViewTopInDate,
  @JsonValue('VNP.Create.Payment')
  vnpCreatePayment,
  @JsonValue('VNP.View.All.History')
  vnpViewAllHistory,
  @JsonValue('VNP.View.All.History.Personal')
  vnpViewAllHistoryPersonal,
}
